# Production Configuration for docsearch
# Environment: Production
# Updated: September 1, 2025

[server]
host = "0.0.0.0"
port = 8080
json_rpc_port = 8081
max_connections = 1000
request_timeout_ms = 30000
shutdown_timeout_ms = 10000

[logging]
level = "info"
format = "json"
file_path = "/app/logs/docsearch.log"
max_file_size_mb = 100
max_files = 10
enable_correlation_ids = true

[search]
# Hybrid search configuration
vector_weight = 0.7
bm25_weight = 0.3
max_results = 50
default_limit = 20
enable_query_enhancement = true
enable_caching = true

[cache]
# Multi-layer caching for production
query_cache_size = 10000
query_cache_ttl_seconds = 3600
embedding_cache_size = 50000
embedding_cache_ttl_seconds = 7200
bm25_cache_size = 20000
bm25_cache_ttl_seconds = 3600
fusion_cache_size = 10000
fusion_cache_ttl_seconds = 1800

[performance]
# Performance thresholds and monitoring
max_query_latency_ms = 350
max_reranking_latency_ms = 900
target_cache_hit_rate = 0.80
max_memory_usage_mb = 2048
gc_threshold_mb = 1536

[observability]
# Metrics and monitoring
enable_metrics = true
metrics_port = 9091
enable_tracing = true
trace_sample_rate = 0.1
health_check_interval_seconds = 30

[storage]
# Data persistence
data_directory = "/app/data"
backup_directory = "/app/data/backups"
enable_auto_backup = true
backup_interval_hours = 6
max_backup_files = 24

[security]
# Production security settings
enable_cors = true
cors_origins = ["https://*.yourdomain.com"]
enable_rate_limiting = true
rate_limit_requests_per_minute = 1000
enable_request_logging = true
max_request_size_mb = 10

[reranking]
# Cross-encoder reranking (when implemented)
enable_reranking = false  # Will enable when ZL-009-004 is complete
model_path = "/app/models/ms-marco-MiniLM-L-6-v2.onnx"
rerank_top_k = 100
batch_size = 32
max_concurrent_requests = 4
