version: '3.8'

# Docker Swarm secrets configuration
secrets:
  jwt_secret:
    external: true
  api_secret_key:
    external: true
  db_password:
    external: true
  vector_db_api_key:
    external: true
  embedding_api_key:
    external: true
  reranking_api_key:
    external: true
  prometheus_password:
    external: true
  grafana_admin_password:
    external: true

services:
  docsearch:
    image: docsearch:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - DOC_INDEXER_PORT=8081
      - LOG_LEVEL=info
      - WORKER_THREADS=4
      - BLOCKING_THREADS=512
      - CACHE_SIZE=10000
    secrets:
      - source: jwt_secret
        target: /run/secrets/jwt_secret
      - source: api_secret_key
        target: /run/secrets/api_secret_key
      - source: vector_db_api_key
        target: /run/secrets/vector_db_api_key
      - source: embedding_api_key
        target: /run/secrets/embedding_api_key
      - source: reranking_api_key
        target: /run/secrets/reranking_api_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    networks:
      - docsearch-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    secrets:
      - source: prometheus_password
        target: /run/secrets/prometheus_password
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
          cpus: '0.3'
    networks:
      - docsearch-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
    secrets:
      - source: grafana_admin_password
        target: /run/secrets/grafana_admin_password
        uid: '472'
        gid: '472'
        mode: 0400
    volumes:
      - grafana-storage:/var/lib/grafana
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
          cpus: '0.2'
    networks:
      - docsearch-network

configs:
  prometheus_config:
    external: true

volumes:
  grafana-storage:

networks:
  docsearch-network:
    driver: overlay
    attachable: true
