apiVersion: v1
kind: Secret
metadata:
  name: docsearch-secrets
  namespace: default
  labels:
    app: docsearch
    component: secrets
type: Opaque
data:
  # Base64 encoded values - replace with actual base64 encoded secrets
  # To encode: echo -n "your_secret" | base64
  
  # Database credentials (if using external database)
  # db-user: <base64_encoded_db_user>
  # db-password: <base64_encoded_db_password>
  # db-host: <base64_encoded_db_host>
  # db-port: <base64_encoded_db_port>
  # db-name: <base64_encoded_db_name>
  
  # Vector database credentials
  # vector-db-api-key: <base64_encoded_vector_db_api_key>
  # vector-db-endpoint: <base64_encoded_vector_db_endpoint>
  
  # API keys
  # embedding-api-key: <base64_encoded_embedding_api_key>
  # reranking-api-key: <base64_encoded_reranking_api_key>
  
  # Security tokens (REQUIRED)
  jwt-secret: <base64_encoded_jwt_secret>
  api-secret-key: <base64_encoded_api_secret_key>

---
apiVersion: v1
kind: Secret
metadata:
  name: docsearch-monitoring-secrets
  namespace: default
  labels:
    app: docsearch
    component: monitoring
type: Opaque
data:
  # Monitoring credentials
  prometheus-user: <base64_encoded_prometheus_user>
  prometheus-password: <base64_encoded_prometheus_password>
  grafana-admin-password: <base64_encoded_grafana_admin_password>

---
# Example ConfigMap for non-sensitive configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: docsearch-config
  namespace: default
  labels:
    app: docsearch
    component: config
data:
  # Server configuration
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "8080"
  DOC_INDEXER_PORT: "8081"
  
  # Logging
  LOG_LEVEL: "info"
  RUST_LOG: "docsearch=info,zero_latency=info"
  
  # Performance
  WORKER_THREADS: "4"
  BLOCKING_THREADS: "512"
  CACHE_SIZE: "10000"
  
  # Feature flags
  ENABLE_METRICS: "true"
  ENABLE_TRACING: "true"
  ENABLE_HEALTH_CHECKS: "true"
